# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-30 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='psw1',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='tel_emil',
            new_name='user_name',
        ),
    ]
