# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-02 01:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_wheel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wheel',
        ),
    ]
