# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-03 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_wheel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods_des',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('trackid', models.CharField(max_length=10)),
                ('pinpai', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'goods_des',
            },
        ),
    ]
